from app.database.sqlserver import SessionLocal

from app.database.models.market_features import MarketFeature
from app.database.models.market_regimes import MarketRegime

from app.regimes.regime_engine import analyze_market


def run_regime_analysis():

    db = SessionLocal()

    try:

        print("Starting Regime Analysis...")

        features = (
            db.query(MarketFeature)
            .order_by(MarketFeature.CreatedAt.desc())
            .limit(50)
            .all()
        )

        for feature in features:

            result = analyze_market(feature)

            regime = MarketRegime(
                Symbol=result["symbol"],
                Timeframe=result["timeframe"],
                Regime=result["regime"],
                Confidence=result["confidence"],
                RecommendedStrategy=result["strategy"],
                Reason="Generated by Regime Engine",
            )

            db.add(regime)

        db.commit()

        print("Regime Analysis Completed")

    except Exception as e:

        print("Regime Error:", e)

    finally:

        db.close()