"""add ml labels

Revision ID: 095577699d38
Revises: 85a7a47a1d78
Create Date: 2026-06-05 22:44:49.834330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '095577699d38'
down_revision: Union[str, Sequence[str], None] = '85a7a47a1d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('future_price', sa.Float(), nullable=True),
    sa.Column('future_return', sa.Float(), nullable=True),
    sa.Column('label', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_labels_id'), 'ml_labels', ['id'], unique=False)
    op.create_index(op.f('ix_ml_labels_symbol'), 'ml_labels', ['symbol'], unique=False)
    op.create_index(op.f('ix_ml_labels_timestamp'), 'ml_labels', ['timestamp'], unique=False)
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_ml_labels_timestamp'), table_name='ml_labels')
    op.drop_index(op.f('ix_ml_labels_symbol'), table_name='ml_labels')
    op.drop_index(op.f('ix_ml_labels_id'), table_name='ml_labels')
    op.drop_table('ml_labels')
    # ### end Alembic commands ###
