"""update mastar signal columns

Revision ID: 1dcaa5d9535d
Revises: 437622cf0808
Create Date: 2026-06-09 23:02:28.072971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dcaa5d9535d'
down_revision: Union[str, Sequence[str], None] = '437622cf0808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
  
    op.add_column('master_signals', sa.Column('long_score', sa.Float(), nullable=True))
    op.add_column('master_signals', sa.Column('short_score', sa.Float(), nullable=True))
    op.add_column('master_signals', sa.Column('orderflow_score', sa.Float(), nullable=True))
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_column('master_signals', 'orderflow_score')
    op.drop_column('master_signals', 'short_score')
    op.drop_column('master_signals', 'long_score')
  
    # ### end Alembic commands ###
