"""update smc engine columns

Revision ID: 297fb1e5d18d
Revises: 6eebbf1cfaed
Create Date: 2026-06-04 22:58:20.015739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '297fb1e5d18d'
down_revision: Union[str, Sequence[str], None] = '6eebbf1cfaed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
