"""Add trade plan tables

Revision ID: 398ceda89d4a
Revises: a1a1d0625624
Create Date: 2026-06-08 08:49:50.398856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '398ceda89d4a'
down_revision: Union[str, Sequence[str], None] = 'a1a1d0625624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('side', sa.String(length=20), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('target1', sa.Float(), nullable=True),
    sa.Column('target2', sa.Float(), nullable=True),
    sa.Column('target3', sa.Float(), nullable=True),
    sa.Column('risk_reward', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###  
    op.drop_table('trade_plans')
    # ### end Alembic commands ###
