"""Add OrderFlowSignal tables

Revision ID: 40f6bd2712fb
Revises: 416d9b53946d
Create Date: 2026-06-09 19:00:21.707646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f6bd2712fb'
down_revision: Union[str, Sequence[str], None] = '416d9b53946d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_flow_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('buy_volume', sa.Float(), nullable=True),
    sa.Column('sell_volume', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('cumulative_delta', sa.Float(), nullable=True),
    sa.Column('buy_pressure', sa.Float(), nullable=True),
    sa.Column('sell_pressure', sa.Float(), nullable=True),
    sa.Column('aggressive_side', sa.String(length=20), nullable=True),
    sa.Column('whale_buy_count', sa.Integer(), nullable=True),
    sa.Column('whale_sell_count', sa.Integer(), nullable=True),
    sa.Column('whale_buy_volume', sa.Float(), nullable=True),
    sa.Column('whale_sell_volume', sa.Float(), nullable=True),
    sa.Column('largest_trade_value', sa.Float(), nullable=True),
    sa.Column('absorption_type', sa.String(length=30), nullable=True),
    sa.Column('absorption_strength', sa.Float(), nullable=True),
    sa.Column('exhaustion_type', sa.String(length=30), nullable=True),
    sa.Column('exhaustion_strength', sa.Float(), nullable=True),
    sa.Column('start_price', sa.Float(), nullable=True),
    sa.Column('end_price', sa.Float(), nullable=True),
    sa.Column('price_change_pct', sa.Float(), nullable=True),
    sa.Column('orderflow_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_flow_signals_symbol'), 'order_flow_signals', ['symbol'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###   
    op.drop_index(op.f('ix_order_flow_signals_symbol'), table_name='order_flow_signals')
    op.drop_table('order_flow_signals')
    # ### end Alembic commands ###
