"""update timeframe coloum

Revision ID: 416d9b53946d
Revises: 63b6633b8f52
Create Date: 2026-06-09 15:24:45.940055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '416d9b53946d'
down_revision: Union[str, Sequence[str], None] = '63b6633b8f52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fusion_signals', sa.Column('timeframe', sa.String(length=5), nullable=True))
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
  
    op.drop_column('fusion_signals', 'timeframe')
    # ### end Alembic commands ###
