"""update type columns

Revision ID: 437622cf0808
Revises: 40f6bd2712fb
Create Date: 2026-06-09 22:46:51.167512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '437622cf0808'
down_revision: Union[str, Sequence[str], None] = '40f6bd2712fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_smc_signals', sa.Column('bos_type', sa.String(length=30), nullable=True))
    op.add_column('market_smc_signals', sa.Column('choch_type', sa.String(length=30), nullable=True))
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('market_smc_signals', 'choch_type')
    op.drop_column('market_smc_signals', 'bos_type')
    # ### end Alembic commands ###
