"""update ml training data fields

Revision ID: 4701951cec72
Revises: ca1c42f08932
Create Date: 2026-06-05 12:50:45.429437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4701951cec72'
down_revision: Union[str, Sequence[str], None] = 'ca1c42f08932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
 
    op.add_column('ml_training_data', sa.Column('entry_price', sa.Float(), nullable=True))
    op.add_column('ml_training_data', sa.Column('exit_price', sa.Float(), nullable=True))
    op.add_column('ml_training_data', sa.Column('evaluated', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ml_training_data', 'evaluated')
    op.drop_column('ml_training_data', 'exit_price')
    op.drop_column('ml_training_data', 'entry_price')
   
    # ### end Alembic commands ###
