"""update ATR Market Feature coloum

Revision ID: 63b6633b8f52
Revises: 911f2da01af6
Create Date: 2026-06-08 21:34:09.670081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63b6633b8f52'
down_revision: Union[str, Sequence[str], None] = '911f2da01af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MarketFeatures', sa.Column('ATR', sa.Float(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('MarketFeatures', 'ATR')
    # ### end Alembic commands ###
