"""add smc engine

Revision ID: 6eebbf1cfaed
Revises: 7fac401dfdf7
Create Date: 2026-06-04 20:14:21.793532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eebbf1cfaed'
down_revision: Union[str, Sequence[str], None] = '7fac401dfdf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_smc_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('timeframe', sa.String(length=10), nullable=True),
    sa.Column('structure', sa.String(length=50), nullable=True),
    sa.Column('previous_high', sa.Float(), nullable=True),
    sa.Column('previous_low', sa.Float(), nullable=True),
    sa.Column('current_high', sa.Float(), nullable=True),
    sa.Column('current_low', sa.Float(), nullable=True),
    sa.Column('order_block_type', sa.String(length=20), nullable=True),
    sa.Column('order_block_high', sa.Float(), nullable=True),
    sa.Column('order_block_low', sa.Float(), nullable=True),
    sa.Column('fvg_detected', sa.Integer(), nullable=True),
    sa.Column('fvg_high', sa.Float(), nullable=True),
    sa.Column('fvg_low', sa.Float(), nullable=True),
    sa.Column('liquidity_sweep', sa.Integer(), nullable=True),
    sa.Column('sweep_direction', sa.String(length=20), nullable=True),
    sa.Column('smc_bias', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_smc_signals_symbol'), 'market_smc_signals', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_smc_signals_symbol'), table_name='market_smc_signals')
    op.drop_table('market_smc_signals')
    # ### end Alembic commands ###
