"""baseline_quantpulse_v3

Revision ID: 7fac401dfdf7
Revises: 
Create Date: 2026-06-04 20:03:33.174510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fac401dfdf7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MarketFeatures',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Symbol', sa.String(length=20), nullable=True),
    sa.Column('Timeframe', sa.String(length=10), nullable=True),
    sa.Column('TrendScore', sa.Float(), nullable=True),
    sa.Column('MomentumScore', sa.Float(), nullable=True),
    sa.Column('VolatilityScore', sa.Float(), nullable=True),
    sa.Column('LiquidityScore', sa.Float(), nullable=True),
    sa.Column('FinalScore', sa.Float(), nullable=True),
    sa.Column('Trend', sa.String(length=50), nullable=True),
    sa.Column('Signal', sa.String(length=50), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_MarketFeatures_Id'), 'MarketFeatures', ['Id'], unique=False)
    op.create_table('MarketOrderFlow',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Symbol', sa.String(length=20), nullable=True),
    sa.Column('Timeframe', sa.String(length=10), nullable=True),
    sa.Column('BuyVolume', sa.Float(), nullable=True),
    sa.Column('SellVolume', sa.Float(), nullable=True),
    sa.Column('Delta', sa.Float(), nullable=True),
    sa.Column('CVD', sa.Float(), nullable=True),
    sa.Column('BuyerStrength', sa.Float(), nullable=True),
    sa.Column('SellerStrength', sa.Float(), nullable=True),
    sa.Column('Absorption', sa.String(length=50), nullable=True),
    sa.Column('Exhaustion', sa.String(length=50), nullable=True),
    sa.Column('FlowSignal', sa.String(length=50), nullable=True),
    sa.Column('Confidence', sa.Float(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('MarketRegimes',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Symbol', sa.String(length=20), nullable=True),
    sa.Column('Timeframe', sa.String(length=10), nullable=True),
    sa.Column('Regime', sa.String(length=50), nullable=True),
    sa.Column('Confidence', sa.Float(), nullable=True),
    sa.Column('RecommendedStrategy', sa.String(length=100), nullable=True),
    sa.Column('Reason', sa.String(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('ai_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('trend_score', sa.Integer(), nullable=True),
    sa.Column('liquidity_score', sa.Integer(), nullable=True),
    sa.Column('derivative_score', sa.Integer(), nullable=True),
    sa.Column('volatility_score', sa.Integer(), nullable=True),
    sa.Column('whale_score', sa.Integer(), nullable=True),
    sa.Column('sentiment_score', sa.Integer(), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=True),
    sa.Column('bias', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_scores_symbol'), 'ai_scores', ['symbol'], unique=False)
    op.create_table('ai_signals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_signals_symbol'), 'ai_signals', ['symbol'], unique=False)
    op.create_table('backtest_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('signal', sa.String(length=20), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('pnl_percent', sa.Float(), nullable=True),
    sa.Column('is_win', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_results_symbol'), 'backtest_results', ['symbol'], unique=False)
    op.create_table('funding_rates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('funding_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_rates_symbol'), 'funding_rates', ['symbol'], unique=False)
    op.create_table('liquidation_heatmaps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('liquidity_above', sa.Float(), nullable=True),
    sa.Column('liquidity_below', sa.Float(), nullable=True),
    sa.Column('above_value', sa.Float(), nullable=True),
    sa.Column('below_value', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('bias', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liquidation_heatmaps_symbol'), 'liquidation_heatmaps', ['symbol'], unique=False)
    op.create_table('liquidations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('side', sa.String(length=10), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liquidity_signals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('signal', sa.String(length=50), nullable=True),
    sa.Column('long_squeeze_probability', sa.Float(), nullable=True),
    sa.Column('short_squeeze_probability', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liquidity_signals_symbol'), 'liquidity_signals', ['symbol'], unique=False)
    op.create_table('market_candles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('candle_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_symbol_timeframe_time', 'market_candles', ['symbol', 'timeframe', 'candle_time'], unique=False)
    op.create_index(op.f('ix_market_candles_candle_time'), 'market_candles', ['candle_time'], unique=False)
    op.create_index(op.f('ix_market_candles_symbol'), 'market_candles', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_candles_timeframe'), 'market_candles', ['timeframe'], unique=False)
    op.create_table('master_signals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('signal', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('risk', sa.String(length=20), nullable=True),
    sa.Column('reasons', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_signals_symbol'), 'master_signals', ['symbol'], unique=False)
    op.create_table('open_interest',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_open_interest_symbol'), 'open_interest', ['symbol'], unique=False)
    op.create_table('signal_quality',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('signal', sa.String(length=20), nullable=True),
    sa.Column('quality_grade', sa.String(length=5), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('trade_allowed', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_quality_symbol'), 'signal_quality', ['symbol'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('base_asset', sa.String(length=20), nullable=True),
    sa.Column('quote_asset', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index(op.f('ix_symbols_id'), 'symbols', ['id'], unique=False)
    op.create_table('whale_signals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('buy_volume', sa.Float(), nullable=True),
    sa.Column('sell_volume', sa.Float(), nullable=True),
    sa.Column('net_flow', sa.Float(), nullable=True),
    sa.Column('whale_score', sa.Float(), nullable=True),
    sa.Column('bias', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whale_signals_symbol'), 'whale_signals', ['symbol'], unique=False)
    op.create_table('whale_trades',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('side', sa.String(length=10), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('value_usd', sa.Float(), nullable=True),
    sa.Column('trade_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whale_trades_symbol'), 'whale_trades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whale_trades_symbol'), table_name='whale_trades')
    op.drop_table('whale_trades')
    op.drop_index(op.f('ix_whale_signals_symbol'), table_name='whale_signals')
    op.drop_table('whale_signals')
    op.drop_index(op.f('ix_symbols_id'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index(op.f('ix_signal_quality_symbol'), table_name='signal_quality')
    op.drop_table('signal_quality')
    op.drop_index(op.f('ix_open_interest_symbol'), table_name='open_interest')
    op.drop_table('open_interest')
    op.drop_index(op.f('ix_master_signals_symbol'), table_name='master_signals')
    op.drop_table('master_signals')
    op.drop_index(op.f('ix_market_candles_timeframe'), table_name='market_candles')
    op.drop_index(op.f('ix_market_candles_symbol'), table_name='market_candles')
    op.drop_index(op.f('ix_market_candles_candle_time'), table_name='market_candles')
    op.drop_index('idx_symbol_timeframe_time', table_name='market_candles')
    op.drop_table('market_candles')
    op.drop_index(op.f('ix_liquidity_signals_symbol'), table_name='liquidity_signals')
    op.drop_table('liquidity_signals')
    op.drop_table('liquidations')
    op.drop_index(op.f('ix_liquidation_heatmaps_symbol'), table_name='liquidation_heatmaps')
    op.drop_table('liquidation_heatmaps')
    op.drop_index(op.f('ix_funding_rates_symbol'), table_name='funding_rates')
    op.drop_table('funding_rates')
    op.drop_index(op.f('ix_backtest_results_symbol'), table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_index(op.f('ix_ai_signals_symbol'), table_name='ai_signals')
    op.drop_table('ai_signals')
    op.drop_index(op.f('ix_ai_scores_symbol'), table_name='ai_scores')
    op.drop_table('ai_scores')
    op.drop_table('MarketRegimes')
    op.drop_table('MarketOrderFlow')
    op.drop_index(op.f('ix_MarketFeatures_Id'), table_name='MarketFeatures')
    op.drop_table('MarketFeatures')
    # ### end Alembic commands ###
