"""update trade plan tables

Revision ID: 911f2da01af6
Revises: 74b65b698316
Create Date: 2026-06-08 11:06:25.286187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '911f2da01af6'
down_revision: Union[str, Sequence[str], None] = '74b65b698316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
 
    op.add_column('trade_plans', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('trade_plans', sa.Column('exit_price', sa.Float(), nullable=True))
    op.add_column('trade_plans', sa.Column('result', sa.String(length=20), nullable=True))
    op.add_column('trade_plans', sa.Column('pnl_percent', sa.Float(), nullable=True))
    op.add_column('trade_plans', sa.Column('closed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_plans', 'closed_at')
    op.drop_column('trade_plans', 'pnl_percent')
    op.drop_column('trade_plans', 'result')
    op.drop_column('trade_plans', 'exit_price')
    op.drop_column('trade_plans', 'status')
   
    # ### end Alembic commands ###
