"""add ml training data

Revision ID: 9cf5573a7087
Revises: d85e612e9f00
Create Date: 2026-06-05 00:18:42.395459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf5573a7087'
down_revision: Union[str, Sequence[str], None] = 'd85e612e9f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_training_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('timeframe', sa.String(length=10), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('momentum_score', sa.Float(), nullable=True),
    sa.Column('volatility_score', sa.Float(), nullable=True),
    sa.Column('regime', sa.String(length=50), nullable=True),
    sa.Column('regime_confidence', sa.Float(), nullable=True),
    sa.Column('cvd', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('smc_bias', sa.String(length=20), nullable=True),
    sa.Column('smc_confidence', sa.Float(), nullable=True),
    sa.Column('signal', sa.String(length=20), nullable=True),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('label', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    
    op.create_index(op.f('ix_ml_training_data_symbol'), 'ml_training_data', ['symbol'], unique=False)
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    
    op.drop_index(op.f('ix_ml_training_data_symbol'), table_name='ml_training_data')
    op.drop_table('ml_training_data')
    # ### end Alembic commands ###
