"""Add fusion signals tables

Revision ID: a1a1d0625624
Revises: 5466d1934ed5
Create Date: 2026-06-08 06:56:24.944935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1a1d0625624'
down_revision: Union[str, Sequence[str], None] = '5466d1934ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fusion_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('decision', sa.String(length=30), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('ml_score', sa.Float(), nullable=True),
    sa.Column('regime_score', sa.Float(), nullable=True),
    sa.Column('orderflow_score', sa.Float(), nullable=True),
    sa.Column('smc_score', sa.Float(), nullable=True),
    sa.Column('liquidation_score', sa.Float(), nullable=True),
    sa.Column('whale_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fusion_signals_symbol'), 'fusion_signals', ['symbol'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_fusion_signals_symbol'), table_name='fusion_signals')
    op.drop_table('fusion_signals')
    # ### end Alembic commands ###
