"""update ml training data

Revision ID: ca1c42f08932
Revises: 9cf5573a7087
Create Date: 2026-06-05 08:49:24.413829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca1c42f08932'
down_revision: Union[str, Sequence[str], None] = '9cf5573a7087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    op.add_column('ml_training_data', sa.Column('buy_pressure', sa.Float(), nullable=True))
    op.add_column('ml_training_data', sa.Column('sell_pressure', sa.Float(), nullable=True))
    op.add_column('ml_training_data', sa.Column('liquidity_sweep', sa.Integer(), nullable=True))
    op.add_column('ml_training_data', sa.Column('order_block', sa.Integer(), nullable=True))
    op.add_column('ml_training_data', sa.Column('fair_value_gap', sa.Integer(), nullable=True))
    op.add_column('ml_training_data', sa.Column('funding_rate', sa.Float(), nullable=True))
    op.add_column('ml_training_data', sa.Column('open_interest_change', sa.Float(), nullable=True))
    op.add_column('ml_training_data', sa.Column('liquidation_pressure', sa.Float(), nullable=True))
    op.add_column('ml_training_data', sa.Column('confidence', sa.Float(), nullable=True))
    op.alter_column('ml_training_data', 'symbol',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ml_training_data', 'symbol',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.drop_column('ml_training_data', 'confidence')
    op.drop_column('ml_training_data', 'liquidation_pressure')
    op.drop_column('ml_training_data', 'open_interest_change')
    op.drop_column('ml_training_data', 'funding_rate')
    op.drop_column('ml_training_data', 'fair_value_gap')
    op.drop_column('ml_training_data', 'order_block')
    op.drop_column('ml_training_data', 'liquidity_sweep')
    op.drop_column('ml_training_data', 'sell_pressure')
    op.drop_column('ml_training_data', 'buy_pressure')
   
    # ### end Alembic commands ###
