"""update smc engine columns

Revision ID: d85e612e9f00
Revises: 297fb1e5d18d
Create Date: 2026-06-04 23:00:26.953732

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d85e612e9f00"
down_revision: Union[str, Sequence[str], None] = "297fb1e5d18d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "market_smc_signals", sa.Column("bos_detected", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "market_smc_signals", sa.Column("choch_detected", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "market_smc_signals", sa.Column("order_block_price", sa.Float(), nullable=True)
    )
    op.add_column(
        "market_smc_signals", sa.Column("fvg_price", sa.Float(), nullable=True)
    )
    op.add_column(
        "market_smc_signals", sa.Column("sweep_price", sa.Float(), nullable=True)
    )
    op.alter_column(
        "market_smc_signals",
        "structure",
        existing_type=sa.VARCHAR(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
        type_=sa.String(length=30),
        existing_nullable=True,
    )
    op.alter_column(
        "market_smc_signals",
        "fvg_detected",
        existing_type=sa.INTEGER(),
        type_=sa.Boolean(),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_market_smc_signals_id"), "market_smc_signals", ["id"], unique=False
    )
    op.drop_column("market_smc_signals", "previous_high")
    op.drop_column("market_smc_signals", "fvg_low")
    op.drop_column("market_smc_signals", "sweep_direction")
    op.drop_column("market_smc_signals", "current_low")
    op.drop_column("market_smc_signals", "order_block_high")
    op.drop_column("market_smc_signals", "fvg_high")
    op.drop_column("market_smc_signals", "order_block_low")
    op.drop_column("market_smc_signals", "current_high")
    op.drop_column("market_smc_signals", "previous_low")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "market_smc_signals",
        sa.Column(
            "previous_low", sa.FLOAT(precision=53), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "market_smc_signals",
        sa.Column(
            "current_high", sa.FLOAT(precision=53), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "market_smc_signals",
        sa.Column(
            "order_block_low",
            sa.FLOAT(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "market_smc_signals",
        sa.Column(
            "fvg_high", sa.FLOAT(precision=53), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "market_smc_signals",
        sa.Column(
            "order_block_high",
            sa.FLOAT(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "market_smc_signals",
        sa.Column(
            "current_low", sa.FLOAT(precision=53), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "market_smc_signals",
        sa.Column(
            "sweep_direction",
            sa.VARCHAR(length=20, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "market_smc_signals",
        sa.Column(
            "fvg_low", sa.FLOAT(precision=53), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "market_smc_signals",
        sa.Column(
            "previous_high", sa.FLOAT(precision=53), autoincrement=False, nullable=True
        ),
    )
    op.drop_index(op.f("ix_market_smc_signals_id"), table_name="market_smc_signals")
    op.alter_column(
        "market_smc_signals",
        "liquidity_sweep",
        existing_type=sa.Boolean(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "market_smc_signals",
        "fvg_detected",
        existing_type=sa.Boolean(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
   
   
