import { useMemo, useState } from "react";
import clsx from "clsx";
import { CheckCircle2, FlaskConical, Lock, Play, ShieldCheck } from "lucide-react";

const API_BASE = import.meta.env.PROD
  ? new URL("/api/", window.location.origin).toString()
  : import.meta.env.VITE_BACKEND_URL || "http://127.0.0.1:8000";
const SYMBOLS = ["BTCUSDT", "ETHUSDT", "XRPUSDT", "SOLUSDT", "BNBUSDT", "DOGEUSDT"];
const TIMEFRAMES = ["1h", "2h", "4h", "1d"];
const POLICIES = ["OFF", "CONFIRM", "REQUIRED"];
const ENGINE_NAMES = ["technical", "ai", "orderflow", "smc", "whale", "funding_oi", "liquidation", "volume", "macro", "regime"];
const DEFAULT_ENGINE_WEIGHTS = { technical: 15, ai: 10, orderflow: 10, smc: 15, whale: 5, funding_oi: 10, liquidation: 5, volume: 10, macro: 5, regime: 10, spot_bias: 5 };

const DEFAULT_PROFILE = {
  strategy_id: "UNIFIED_COMPOSITE", mode: "MANUAL_REVIEW",
  execution: { paper_only: true, live_enabled: false, allowed_symbols: ["BTCUSDT", "ETHUSDT"] },
  engines: { technical: "REQUIRED", ai: "CONFIRM", orderflow: "CONFIRM", smc: "REQUIRED", whale: "CONFIRM", funding_oi: "CONFIRM", liquidation: "CONFIRM", volume: "REQUIRED", macro: "CONFIRM", regime: "REQUIRED", spot_bias: { "1h": "REQUIRED", "2h": "REQUIRED", "4h": "REQUIRED", "1d": "CONFIRM" } },
  engine_weights: DEFAULT_ENGINE_WEIGHTS,
  bias_policy: { required_direction: "ALIGN", minimum_confirmations: 3, daily_opposite_blocks: true, macro_opposite_blocks: false, stale_input_action: "WAIT", contradiction_action: "WAIT" },
  entry: { mode: "BREAKOUT_RETEST", minimum_confidence: 70, maximum_entry_slippage_percent: 0.05 },
  exit: { target1_reward_to_risk: 1, target1_close_fraction: 0.5, target2_reward_to_risk: 2, trailing_activation_r: 1, protection_mode: "BREAKEVEN_AFTER_T1", maximum_hold_hours: 48 },
  risk: { stop_mode: "STRUCTURE_ATR", atr_multiplier: 1.5, risk_per_trade_percent: 0.25, maximum_leverage: 1, maximum_open_positions: 2, daily_loss_limit_percent: 1, weekly_loss_limit_percent: 3, one_position_per_symbol: true },
};

function normalizeProfile(value) {
  return {
    ...DEFAULT_PROFILE, ...(value || {}),
    execution: { ...DEFAULT_PROFILE.execution, ...(value?.execution || {}) },
    engines: { ...DEFAULT_PROFILE.engines, ...(value?.engines || {}), spot_bias: { ...DEFAULT_PROFILE.engines.spot_bias, ...(value?.engines?.spot_bias || {}) } },
    engine_weights: { ...DEFAULT_ENGINE_WEIGHTS, ...(value?.engine_weights || {}) },
    bias_policy: { ...DEFAULT_PROFILE.bias_policy, ...(value?.bias_policy || {}) },
    entry: { ...DEFAULT_PROFILE.entry, ...(value?.entry || {}) }, exit: { ...DEFAULT_PROFILE.exit, ...(value?.exit || {}) }, risk: { ...DEFAULT_PROFILE.risk, ...(value?.risk || {}) },
  };
}
function apiUrl(path) { return new URL(String(path).replace(/^\/+/, ""), API_BASE); }
async function callApi(path, body) {
  const response = await fetch(apiUrl(path), { method: "POST", credentials: "include", headers: { Accept: "application/json", "Content-Type": "application/json" }, body: JSON.stringify(body) });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(payload.detail || "Unified strategy request failed");
  return payload;
}
function NumberInput({ label, value, onChange, step = "0.1", min = "0" }) {
  return <label className="block text-xs text-slate-500"><span>{label}</span><input type="number" min={min} step={step} value={value} onChange={(event) => onChange(Number(event.target.value))} className="mt-1 w-full rounded-lg border border-white/10 bg-white px-2.5 py-2 text-sm text-slate-900 outline-none focus:border-cyan-400" /></label>;
}

export default function UnifiedStrategyPage() {
  const [profile, setProfile] = useState(() => { try { return normalizeProfile(JSON.parse(localStorage.getItem("quantpulse:unified-profile"))); } catch { return normalizeProfile(DEFAULT_PROFILE); } });
  const [symbol, setSymbol] = useState("BTCUSDT"); const [timeframe, setTimeframe] = useState("1h"); const [result, setResult] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const requiredCount = useMemo(() => Object.values(profile.engines).filter((value) => typeof value === "string" && value === "REQUIRED").length, [profile.engines]);
  const weightTotal = useMemo(() => Object.values(profile.engine_weights).reduce((total, value) => total + Number(value || 0), 0), [profile.engine_weights]);
  const weightsValid = Math.abs(weightTotal - 100) < 0.01;
  const update = (path, value) => setProfile((current) => { const next = structuredClone(current); let target = next; path.slice(0, -1).forEach((key) => { target = target[key]; }); target[path[path.length - 1]] = value; localStorage.setItem("quantpulse:unified-profile", JSON.stringify(next)); return next; });
  const toggleSymbol = (value) => update(["execution", "allowed_symbols"], profile.execution.allowed_symbols.includes(value) ? profile.execution.allowed_symbols.filter((item) => item !== value) : [...profile.execution.allowed_symbols, value]);
  const submit = async (kind) => { setBusy(true); setError(""); try { setResult(await callApi(kind === "validate" ? "unified-strategy/validate" : `unified-strategy/evaluate/${symbol}?timeframe=${timeframe}`, profile)); } catch (requestError) { setError(requestError.message); } finally { setBusy(false); } };

  return <section className="border-b border-white/5"><div className="mx-auto w-full max-w-[1680px] px-4 py-4 sm:px-6 lg:px-8">
    <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="text-[11px] uppercase tracking-[0.22em] text-slate-500">Paper strategy studio</div><h2 className="mt-1 text-xl font-semibold tracking-tight text-white">Unified Composite Strategy</h2><p className="mt-1 max-w-3xl text-sm text-slate-400">Configure gates and contribution weights for a single reviewable paper strategy.</p></div><div className="flex flex-wrap gap-2"><span className="inline-flex items-center gap-1.5 rounded-full border border-emerald-400/25 bg-emerald-500/10 px-3 py-1.5 text-xs font-semibold text-emerald-700"><Lock className="h-3.5 w-3.5" /> Live trading disabled</span><span className="inline-flex items-center gap-1.5 rounded-full border border-cyan-400/25 bg-cyan-500/10 px-3 py-1.5 text-xs font-semibold text-cyan-700"><FlaskConical className="h-3.5 w-3.5" /> Paper only</span></div></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.4fr_1fr]"><div className="space-y-4">
      <Panel title="Execution and symbol scope"><div className="grid gap-3 md:grid-cols-2"><label className="text-xs text-slate-500">Mode<select value={profile.mode} onChange={(event) => update(["mode"], event.target.value)} className="mt-1 w-full rounded-lg border border-white/10 bg-white px-2.5 py-2 text-sm text-slate-900"><option>MANUAL_REVIEW</option><option>PAPER_AUTO</option></select></label><label className="text-xs text-slate-500">Evaluation symbol<select value={symbol} onChange={(event) => setSymbol(event.target.value)} className="mt-1 w-full rounded-lg border border-white/10 bg-white px-2.5 py-2 text-sm text-slate-900">{SYMBOLS.map((item) => <option key={item}>{item}</option>)}</select></label></div><div className="mt-3 flex flex-wrap gap-2">{SYMBOLS.map((item) => <button key={item} type="button" onClick={() => toggleSymbol(item)} className={clsx("rounded-lg border px-2.5 py-1.5 text-xs", profile.execution.allowed_symbols.includes(item) ? "border-cyan-400/40 bg-cyan-500/10 text-cyan-700" : "border-white/10 bg-slate-50 text-slate-500")}>{item}</button>)}</div></Panel>
      <Panel title="Engine policies"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{ENGINE_NAMES.map((name) => <label key={name} className="text-xs text-slate-500"><span className="capitalize">{name.replace("_", " / ")}</span><select value={profile.engines[name]} onChange={(event) => update(["engines", name], event.target.value)} className="mt-1 w-full rounded-lg border border-white/10 bg-white px-2.5 py-2 text-sm text-slate-900">{POLICIES.map((policy) => <option key={policy}>{policy}</option>)}</select></label>)}</div><div className="mt-3 rounded-lg border border-white/10 bg-slate-50 p-3"><div className="text-xs font-semibold text-slate-700">Spot bias by timeframe</div><div className="mt-2 grid gap-2 sm:grid-cols-4">{TIMEFRAMES.map((item) => <label key={item} className="text-xs text-slate-500">{item}<select value={profile.engines.spot_bias[item]} onChange={(event) => update(["engines", "spot_bias", item], event.target.value)} className="mt-1 w-full rounded-lg border border-white/10 bg-white px-2 py-2 text-sm text-slate-900">{POLICIES.map((policy) => <option key={policy}>{policy}</option>)}</select></label>)}</div></div></Panel>
      <Panel title="Execution contribution weights"><p className="text-xs leading-5 text-slate-500">Current defaults show each engine’s share of the composite score. Edit them later per coin, but keep the total at exactly 100%.</p><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{[...ENGINE_NAMES, "spot_bias"].map((name) => <label key={name} className="text-xs text-slate-500"><span className="capitalize">{name.replace("_", " / ")}</span><div className="relative mt-1"><input type="number" min="0" max="100" step="1" value={profile.engine_weights[name]} onChange={(event) => update(["engine_weights", name], Number(event.target.value))} className="w-full rounded-lg border border-white/10 bg-white px-2.5 py-2 pr-8 text-sm text-slate-900 outline-none focus:border-cyan-400" /><span className="pointer-events-none absolute right-2.5 top-2 text-xs text-slate-400">%</span></div></label>)}</div><div className={clsx("mt-3 rounded-lg border px-3 py-2 text-xs font-semibold", weightsValid ? "border-emerald-400/30 bg-emerald-500/10 text-emerald-700" : "border-rose-400/30 bg-rose-500/10 text-rose-700")}>Total contribution: {weightTotal.toFixed(2)}% {weightsValid ? "• ready" : "• adjust to 100% before validation"}</div></Panel>
      <Panel title="Entry, exit, and risk controls"><div className="grid gap-4 md:grid-cols-3"><div className="space-y-3"><label className="text-xs text-slate-500">Entry mode<select value={profile.entry.mode} onChange={(event) => update(["entry", "mode"], event.target.value)} className="mt-1 w-full rounded-lg border border-white/10 bg-white px-2.5 py-2 text-sm text-slate-900"><option>BREAKOUT_RETEST</option><option>PULLBACK</option><option>MARKET</option></select></label><NumberInput label="Minimum confidence" value={profile.entry.minimum_confidence} onChange={(value) => update(["entry", "minimum_confidence"], value)} /></div><div className="space-y-3"><NumberInput label="Target 1 R:R" value={profile.exit.target1_reward_to_risk} onChange={(value) => update(["exit", "target1_reward_to_risk"], value)} /><NumberInput label="Target 2 R:R" value={profile.exit.target2_reward_to_risk} onChange={(value) => update(["exit", "target2_reward_to_risk"], value)} /><NumberInput label="Maximum hold (hours)" value={profile.exit.maximum_hold_hours} onChange={(value) => update(["exit", "maximum_hold_hours"], value)} step="1" /></div><div className="space-y-3"><NumberInput label="Risk per trade (%)" value={profile.risk.risk_per_trade_percent} onChange={(value) => update(["risk", "risk_per_trade_percent"], value)} /><NumberInput label="ATR stop multiplier" value={profile.risk.atr_multiplier} onChange={(value) => update(["risk", "atr_multiplier"], value)} /><NumberInput label="Daily loss limit (%)" value={profile.risk.daily_loss_limit_percent} onChange={(value) => update(["risk", "daily_loss_limit_percent"], value)} /></div></div></Panel>
    </div><div className="space-y-4"><Panel title="Bias and evaluation"><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-500">Evaluation timeframe<select value={timeframe} onChange={(event) => setTimeframe(event.target.value)} className="mt-1 w-full rounded-lg border border-white/10 bg-white px-2.5 py-2 text-sm text-slate-900">{TIMEFRAMES.map((item) => <option key={item}>{item}</option>)}</select></label><NumberInput label="Minimum confirmations" value={profile.bias_policy.minimum_confirmations} onChange={(value) => update(["bias_policy", "minimum_confirmations"], value)} step="1" /></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><Metric label="Required engines" value={requiredCount} /><Metric label="Allowed symbols" value={profile.execution.allowed_symbols.length} /></div><div className="mt-3 rounded-lg border border-amber-400/20 bg-amber-500/10 p-3 text-xs leading-5 text-amber-800">Evaluation is advisory and paper-only. It never creates live orders. Contradictory or stale inputs return WAIT.</div>{!weightsValid && <div className="mt-3 rounded-lg border border-rose-400/20 bg-rose-500/10 p-3 text-xs leading-5 text-rose-700">Set engine contribution weights to 100% before running a validation or evaluation.</div>}<div className="mt-3 flex flex-wrap gap-2"><button type="button" disabled={busy || !weightsValid} onClick={() => submit("validate")} className="inline-flex items-center gap-2 rounded-lg border border-cyan-400/30 bg-cyan-500/10 px-3 py-2 text-sm font-semibold text-cyan-700 disabled:opacity-50"><ShieldCheck className="h-4 w-4" />{busy ? "Checking…" : "Validate profile"}</button><button type="button" disabled={busy || !weightsValid} onClick={() => submit("evaluate")} className="inline-flex items-center gap-2 rounded-lg bg-cyan-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50"><Play className="h-4 w-4" />Evaluate {symbol}</button></div></Panel>{error ? <div role="alert" className="rounded-lg border border-rose-400/20 bg-rose-500/10 p-3 text-sm text-rose-700">{error}</div> : null}{result ? <Panel title="Latest result"><div className="flex items-center gap-2 text-sm font-semibold text-slate-800"><CheckCircle2 className="h-4 w-4 text-emerald-600" />{result.status || result.decision || "Response received"}</div><pre className="mt-3 max-h-[32rem] overflow-auto rounded-lg bg-slate-950 p-3 text-xs leading-5 text-slate-100">{JSON.stringify(result, null, 2)}</pre></Panel> : <Panel title="How to use"><p className="text-sm leading-6 text-slate-500">Tune a coin’s gates and weights, validate the profile, then evaluate one symbol and timeframe. Use MANUAL_REVIEW while calibrating; PAPER_AUTO remains paper-only and respects the configured gates.</p></Panel>}</div>
    </div></div></section>;
}
function Panel({ title, children }) { return <section className="rounded-xl border border-white/10 bg-white p-4 shadow-sm"><h3 className="text-sm font-semibold text-slate-800">{title}</h3><div className="mt-3">{children}</div></section>; }
function Metric({ label, value }) { return <div className="rounded-lg border border-white/10 bg-slate-50 p-3"><div className="text-[10px] uppercase tracking-[0.16em] text-slate-500">{label}</div><div className="mt-1 text-lg font-semibold text-slate-900">{value}</div></div>; }
