from datetime import datetime

from sqlalchemy import Column, DateTime, Float, Integer, String

from app.database.sqlserver import Base


class PaperTrade(Base):
    __tablename__ = "paper_trades"

    id = Column(Integer, primary_key=True)
    trade_plan_id = Column(Integer, index=True)
    risk_decision_id = Column(Integer, index=True)
    symbol = Column(String(30), index=True)
    side = Column(String(20))
    entry_price = Column(Float)
    stop_loss = Column(Float)
    target1 = Column(Float)
    target2 = Column(Float)
    position_size = Column(Float)
    risk_reward = Column(Float)
    risk_percent = Column(Float)
    confidence = Column(Float)
    mode = Column(String(20), nullable=True)
    entry_timeframe = Column(String(10), nullable=True)
    timeframe_stack = Column(String(40), nullable=True)
    regime = Column(String(50), nullable=True)
    thesis_id = Column(Integer, nullable=True, index=True)
    data_generation_id = Column(String(100), nullable=True, index=True)
    exit_policy = Column(String(50), nullable=True)
    initial_stop_loss = Column(Float, nullable=True)
    target1_fraction = Column(Float, nullable=True)
    remaining_position_fraction = Column(Float, nullable=True)
    max_hold_hours = Column(Integer, nullable=True)
    target1_hit_at = Column(DateTime, nullable=True)
    target1_exit_price = Column(Float, nullable=True)
    exit_monitor_timeframe = Column(String(10), nullable=True)
    last_exit_evaluated_at = Column(DateTime, nullable=True)
    paper_capital_at_entry_inr = Column(Float, nullable=True)
    allocation_percent = Column(Float, nullable=True)
    position_notional_inr = Column(Float, nullable=True)
    leverage = Column(Float, nullable=True)
    margin_used_inr = Column(Float, nullable=True)
    partial_realized_pnl_inr = Column(Float, nullable=True)
    realized_pnl_inr = Column(Float, nullable=True)
    validation_contract_version = Column(String(100), nullable=True)
    fill_model_version = Column(String(100), nullable=True)
    planned_entry_price = Column(Float, nullable=True)
    entry_slippage_percent = Column(Float, nullable=True)
    exit_slippage_percent = Column(Float, nullable=True)
    funding_rate_snapshot = Column(Float, nullable=True)
    funding_event_count = Column(Integer, nullable=True)
    funding_cost_percent = Column(Float, nullable=True)
    open_interest_snapshot = Column(Float, nullable=True)
    open_interest_change_percent = Column(Float, nullable=True)
    fee_bps = Column(Float, default=7.5)
    fees_percent = Column(Float, nullable=True)
    gross_pnl_percent = Column(Float, nullable=True)
    status = Column(String(20), default="OPEN", index=True)
    exit_price = Column(Float, nullable=True)
    result = Column(String(20), nullable=True)
    pnl_percent = Column(Float, nullable=True)
    opened_at = Column(DateTime, default=datetime.utcnow)
    closed_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
